# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

windowrule = center true, match:class jetbrains-.*, match:title splash, match:float true
windowrule = no_focus true, match:class jetbrains-.*, match:title splash, match:float true

windowrule = no_focus true, match:class jetbrains-.*, match:title win.*, match:float true

windowrule = no_blur true, match:class jetbrains-.*, match:float true
windowrule = no_initial_focus true, match:class jetbrains-.*, match:float true
windowrule = opacity 1 override 1 override 1, match:class jetbrains-.*, match:float true

# Pavucontrol
windowrule {
    name = pavucontrol
    match:class = (.*pavucontrol-qt*)
    float = true
    center = true
    pin = true
    size = 1200 800
}

windowrule {
    name = arctis-manager
    match:class = (.*lam*)
    float = true
    center = true
    pin = true
    size = 1200 800
}

windowrule {
    name = nwg-displays
    match:class = (nwg-displays)
    float = true
    center = true
    size = 1200 800
}

windowrule {
    name = missioncenter
    match:class = (io.missioncenter.MissionCenter)
    float = true
    center = true
    pin = true
    size = 1200 800
}

# Picture-in-Picture
windowrule {
    name = Picture-in-Picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = true
    pin = true
    center = true
}

# General floating
windowrule {
    name = dotfiles-floating
    match:class = (dotfiles-floating)
    float = true
    center = true
    size = 1000 700
}

# Dotfiles Sidepad
windowrule {
    name = dotfiles-sidepad
    match:class = (dotfiles-sidepad)
    float = true
    pin = true
    center = true
    size = 1000 700
}